
version: "3.9"
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks: [appnet]

  redis:
    image: redis:7
    restart: unless-stopped
    networks: [appnet]

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - miniodata:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks: [appnet]

  api:
    build: ./backend
    env_file: .env
    depends_on: [db, redis, minio]
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks: [appnet]

  web:
    build: ./web
    env_file: .env
    depends_on: [api]
    ports:
      - "5173:5173"
    restart: unless-stopped
    networks: [appnet]

  nginx:
    image: nginx:alpine
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/letsencrypt
      - ./web/dist:/usr/share/nginx/html:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on: [web, api]
    networks: [appnet]

volumes:
  pgdata: {}
  miniodata: {}
  certs: {}

networks:
  appnet: {}
